openapi: 3.0.1
  info:
    title: test
    version: 1.0.0
  x-amazon-apigateway-request-validators:
    all:
      validateRequestBody: true
      validateRequestParameters: true
  paths:
    /:
      get:
        parameters:
          - name: page
            in: query
            required: true
            schema:
              type: string
          - name: type
            in: query
            required: true
            schema:
              type: string
        responses:
          '200':
            description: 200 response
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: hello world
        x-amazon-apigateway-request-validator: all
        x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "http://petstore.execute-api.us-east-1.amazonaws.com/petstore/pets"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestParameters:
          integration.request.querystring.page: "method.request.querystring.page"
          integration.request.querystring.type: "method.request.querystring.type"
        passthroughBehavior: "when_no_match"
        type: "http"
